MLK-13917 pxp: fix build error for pxp library in user space
Fix following build error by changing type to '__u64'.

include/uapi/linux/pxp_dma.h:230:2: error: unknown type name 'u64'
   u64 lut_sels;
   ^~~

Signed-off-by: Robby Cai <robby.cai@nxp.com>
(cherry picked from commit e47cefd49dd90548c90e0ee6a8ef9680f45c4d4b)