MLK-13191: dts: imx6q: pop arm2: fix dtb build error
Error: arch/arm/boot/dts/imx6q-pop-arm2.dts:61.26-27 syntax error
FATAL ERROR: Unable to parse input tree
scripts/Makefile.lib:293: recipe for target
'arch/arm/boot/dts/imx6q-pop-arm2.dtb' failed
make[1]: *** [arch/arm/boot/dts/imx6q-pop-arm2.dtb] Error 1
arch/arm/Makefile:327: recipe for target 'dtbs' failed
make: *** [dtbs] Error 2
make: *** Waiting for unfinished jobs....

Include gpio dt-bindings header file to resolve GPIO_ACTIVE_HIGH macro

Signed-off-by: Haibo Chen <haibo.chen@nxp.com>
Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
(Cherry picked from commit 089fc355a17596fa709abc0708bda97c1567c947)