MLK-12617 mmc: Fix compile error when CONFIG_MMC=m
When CONFIG_MMC=m, compile error shows up

ERROR: "of_alias_max_index" [drivers/mmc/core/mmc_core.ko] undefined!
ERROR: "mmc_get_reserved_index" [drivers/mmc/card/mmc_block.ko] undefined!
ERROR: "mmc_first_nonreserved_index" [drivers/mmc/card/mmc_block.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
make: *** Waiting for unfinished jobs....

This patch export the upper three symbol for module runtime load.

Signed-off-by: Haibo Chen <haibo.chen@nxp.com>
(cherry picked from commit 3b2520f17d427b8fa8db37a6d9a4311f20c29036)